### ISSUE TITLE
第三章 网络连接问题

### ISSUE THREAD

**Issue by happybear1015** [Chinese-NLP-book/rasa_chinese_book_code#4]
请教一下，第三章的报时机器人，为什么会出现下面的问题呢？python是3.9，系统是windows11.

Your input ->  现在几点了？
2022-05-06 16:40:28 ERROR    rasa.core.actions.action  - Failed to run custom action 'action_query_date'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:default [远程计算机拒绝网络连接。]
2022-05-06 16:40:28 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_query_date'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.dows_events.py", line 599, in finish_connect
Traceback (most recent call last):
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "D:\anaconda\envs\rasa2\lib\asyncio\base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "D:\anaconda\envs\rasa2\lib\asyncio\base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(ite-packages\rasa\core\actions\action.py", line 742, in run
  File "D:\anaconda\envs\rasa2\lib\asyncio\base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)ckages\rasa\utils\endpoints.py", line 164, in request
  File "D:\anaconda\envs\rasa2\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)tp\client.py", line 1117, in __aenter__
  File "D:\anaconda\envs\rasa2\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)ckages\aiohttp\client.py", line 520, in _request
  File "D:\anaconda\envs\rasa2\lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()a\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 535, in connect
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
The above exception was the direct cause of the following exception:eout)
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 1051, in _create_direct_connection
Traceback (most recent call last):
  File "D:\anaconda\envs\rasa2\lib\site-packages\rasa\core\actions\action.py", line 742, in runirect_connection
    response: Any = await self.action_endpoint.request(
  File "D:\anaconda\envs\rasa2\lib\site-packages\rasa\utils\endpoints.py", line 164, in requestte_connection
    async with session.request(ection_key, exc) from exc
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__ault [远程计算机拒绝网络连接。]
    self._resp = await self._coro
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)essor.py", line 869, in _run_action
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout).py", line 774, in run
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 1051, in _create_direct_connection
    raise last_excions.RasaException: Failed to execute custom action.
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\anaconda\envs\rasa2\lib\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:5055 ssl:default [远程计算机拒绝网络连接。]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\envs\rasa2\lib\site-packages\rasa\core\processor.py", line 869, in _run_action
    events = await action.run(
  File "D:\anaconda\envs\rasa2\lib\site-packages\rasa\core\actions\action.py", line 774, in run
    raise RasaException("Failed to execute custom action.")
rasa.shared.exceptions.RasaException: Failed to execute custom action.

**Comment by happybear1015** [comment]
自行解决了！原因是：没有运行动作服务器：rasa run actions
