### ISSUE TITLE
安装完成后，运行rasa train时遇到cache_dir是空的，该如何为它设值？

### ISSUE THREAD

**Issue by jhj033** [Chinese-NLP-book/rasa_chinese_book_code#9]
The problem resolved!

**Comment by jhj033** [comment]
> Traceback (most recent call last): File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/engine/graph.py", line 398, in _load_component **kwargs, File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/engine/graph.py", line 219, in load return cls.create(config, model_storage, resource, execution_context) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py", line 100, in create return cls(config, execution_context) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py", line 67, in **init** self._load_model_instance() File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py", line 153, in _load_model_instance self.model_weights, cache_dir=self.cache_dir File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 911, in from_pretrained return cls._from_pretrained(*inputs, **kwargs) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 1014, in _from_pretrained list(cls.vocab_files_names.values()), OSError: Model name 'bert-base-chinese' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). We assumed 'bert-base-chinese' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/dell/anaconda3/envs/rasa_zh/bin/rasa", line 8, in sys.exit(main()) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/**main**.py", line 121, in main cmdline_arguments.func(cmdline_arguments) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/cli/train.py", line 59, in train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True)) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/cli/train.py", line 103, in run_training finetuning_epoch_fraction=args.epoch_fraction, File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/api.py", line 117, in train finetuning_epoch_fraction=finetuning_epoch_fraction, File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/model_training.py", line 181, in train **(nlu_additional_arguments or {}), File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/model_training.py", line 242, in _train_graph is_finetuning=is_finetuning, File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/engine/training/graph_trainer.py", line 108, in train graph_runner.run(inputs={PLACEHOLDER_IMPORTER: importer}) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/engine/runner/dask.py", line 106, in run dask_result = dask.get(run_graph, run_targets) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/local.py", line 558, in get_sync **kwargs, File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/local.py", line 496, in get_async for key, res_info, failed in queue_get(queue).result(): File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/concurrent/futures/_base.py", line 428, in result return self.__get_result() File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result raise self._exception File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/local.py", line 538, in submit fut.set_result(fn(*args, **kwargs)) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/local.py", line 234, in batch_execute_tasks return [execute_task(*a) for a in it] File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/local.py", line 234, in return [execute_task(_a) for a in it] File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/local.py", line 225, in execute_task result = pack_exception(e, dumps) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/local.py", line 220, in execute_task result = _execute_task(task, data) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task return func(_(_execute_task(a, cache) for a in args)) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/engine/graph.py", line 448, in **call** self._load_component(**constructor_kwargs) File "/home/dell/anaconda3/envs/rasa_zh/lib/python3.7/site-packages/rasa/engine/graph.py", line 407, in _load_component ) from e rasa.engine.exceptions.GraphComponentException: Error initializing graph component for node 'run_LanguageModelFeaturizer1'.
